Export positions to PNG.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3930,6 +3930,7 @@ _ACEOF
 fi
 
 
+
 echo "$as_me:$LINENO: checking for ANSI C header files" >&5
 echo $ECHO_N "checking for ANSI C header files... $ECHO_C" >&6
 if test "${ac_cv_header_stdc+set}" = set; then
@@ -10275,6 +10276,78 @@ fi
 
 
 
+
+echo "$as_me:$LINENO: checking for png_create_info_struct in -lpng" >&5
+echo $ECHO_N "checking for png_create_info_struct in -lpng... $ECHO_C" >&6
+if test "${ac_cv_lib_png_png_create_info_struct+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lpng  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char png_create_info_struct ();
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+png_create_info_struct ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_png_png_create_info_struct=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_lib_png_png_create_info_struct=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_png_png_create_info_struct" >&5
+echo "${ECHO_T}$ac_cv_lib_png_png_create_info_struct" >&6
+if test $ac_cv_lib_png_png_create_info_struct = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBPNG 1
+_ACEOF
+
+  LIBS="-lpng $LIBS"
+
+fi
+
+if test "$ac_cv_lib_png_png_create_info_struct" == yes; then
+   PNG_LIBS='-lpng -lz'
+fi
+
+
+
+
 	ac_expanded=`(
 	    test "x$prefix" = xNONE && prefix="$ac_default_prefix"
 	    test "x$exec_prefix" = xNONE && exec_prefix="${prefix}"
@@ -13425,6 +13498,7 @@ s,@ARTSC_CFLAGS@,$ARTSC_CFLAGS,;t t
 s,@ARTSC_LIBS@,$ARTSC_LIBS,;t t
 s,@NAS_LIBS@,$NAS_LIBS,;t t
 s,@NAS_CFLAGS@,$NAS_CFLAGS,;t t
+s,@PNG_LIBS@,$PNG_LIBS,;t t
 s,@MKINSTALLDIRS@,$MKINSTALLDIRS,;t t
 s,@MSGFMT@,$MSGFMT,;t t
 s,@GMSGFMT@,$GMSGFMT,;t t
