Don't bother compiling luxi.c if not using freetype.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9553,11 +9553,7 @@ fi                 # test "$FT2_CONFIG" = "no"
 if test x$no_ft = x ; then
    echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
-
-cat >>confdefs.h <<\_ACEOF
-#define HAVE_FREETYPE 1
-_ACEOF
-
+   have_freetype=yes
 else
    echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
@@ -9586,6 +9582,23 @@ echo "${ECHO_T}no" >&6
 fi
 
 
+
+if test "$have_freetype" = "yes"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_FREETYPE 1
+_ACEOF
+
+fi
+
+
+if test "$have_freetype" = "yes"; then
+  USE_FREETYPE_TRUE=
+  USE_FREETYPE_FALSE='#'
+else
+  USE_FREETYPE_TRUE='#'
+  USE_FREETYPE_FALSE=
+fi
 
 
 
@@ -12698,6 +12711,13 @@ echo "$as_me: error: conditional \"XML_MANUAL\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${USE_FREETYPE_TRUE}" && test -z "${USE_FREETYPE_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"USE_FREETYPE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"USE_FREETYPE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${USE_SOUND_TRUE}" && test -z "${USE_SOUND_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"USE_SOUND\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -13288,6 +13308,8 @@ s,@XML_MANUAL_FALSE@,$XML_MANUAL_FALSE,;t t
 s,@FT2_CONFIG@,$FT2_CONFIG,;t t
 s,@FT2_CFLAGS@,$FT2_CFLAGS,;t t
 s,@FT2_LIBS@,$FT2_LIBS,;t t
+s,@USE_FREETYPE_TRUE@,$USE_FREETYPE_TRUE,;t t
+s,@USE_FREETYPE_FALSE@,$USE_FREETYPE_FALSE,;t t
 s,@USE_SOUND_TRUE@,$USE_SOUND_TRUE,;t t
 s,@USE_SOUND_FALSE@,$USE_SOUND_FALSE,;t t
 s,@ESD_CONFIG@,$ESD_CONFIG,;t t
