check for python

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -868,6 +868,7 @@ Optional Packages:
   --with-libart-exec-prefix=PFX Exec prefix where LIBART is installed (optional)
   --with-guile            use the Guile extensibility language
   --with-guile-prefix=PREFIX Prefix where Guile is installed (optional)
+  --with-python       provide Python script availabity inside gnubg
   --with-ft-prefix=PREFIX
                           Prefix where FreeType is installed (optional)
   --with-ft-exec-prefix=PREFIX
@@ -9760,6 +9761,238 @@ fi
 fi
 
 
+
+# Check whether --with-python or --without-python was given.
+if test "${with_python+set}" = set; then
+  withval="$with_python"
+
+fi;
+if test "$with_python" = "no"; then
+   no_python=yes
+else
+
+
+
+
+        if test -n "$PYTHON"; then
+      # If the user set $PYTHON, use it and don't search something else.
+      echo "$as_me:$LINENO: checking whether $PYTHON version >= 1.5" >&5
+echo $ECHO_N "checking whether $PYTHON version >= 1.5... $ECHO_C" >&6
+      prog="import sys, string
+# split strings by '.' and convert to numeric.  Append some zeros
+# because we need at least 4 digits for the hex conversion.
+minver = map(int, string.split('1.5', '.')) + [0, 0, 0]
+minverhex = 0
+for i in xrange(0, 4): minverhex = (minverhex << 8) + minver[i]
+sys.exit(sys.hexversion < minverhex)"
+  if { echo "$as_me:$LINENO: $PYTHON -c "$prog"" >&5
+   ($PYTHON -c "$prog") >&5 2>&5
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+else
+  { { echo "$as_me:$LINENO: error: too old" >&5
+echo "$as_me: error: too old" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+    else
+      # Otherwise, try each interpreter until we find one that satisfies
+      # VERSION.
+      echo "$as_me:$LINENO: checking for a Python interpreter with version >= 1.5" >&5
+echo $ECHO_N "checking for a Python interpreter with version >= 1.5... $ECHO_C" >&6
+if test "${am_cv_pathless_PYTHON+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+	for am_cv_pathless_PYTHON in python python2 python2.2 python2.1 python2.0 python1.6 python1.5 : ; do
+          if test "$am_cv_pathless_PYTHON" = : ; then
+            { { echo "$as_me:$LINENO: error: no suitable Python interpreter found" >&5
+echo "$as_me: error: no suitable Python interpreter found" >&2;}
+   { (exit 1); exit 1; }; }
+	  fi
+          prog="import sys, string
+# split strings by '.' and convert to numeric.  Append some zeros
+# because we need at least 4 digits for the hex conversion.
+minver = map(int, string.split('1.5', '.')) + [0, 0, 0]
+minverhex = 0
+for i in xrange(0, 4): minverhex = (minverhex << 8) + minver[i]
+sys.exit(sys.hexversion < minverhex)"
+  if { echo "$as_me:$LINENO: $am_cv_pathless_PYTHON -c "$prog"" >&5
+   ($am_cv_pathless_PYTHON -c "$prog") >&5 2>&5
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; then
+  break
+fi
+
+        done
+fi
+echo "$as_me:$LINENO: result: $am_cv_pathless_PYTHON" >&5
+echo "${ECHO_T}$am_cv_pathless_PYTHON" >&6
+      # Set $PYTHON to the absolute path of $am_cv_pathless_PYTHON.
+      # Extract the first word of "$am_cv_pathless_PYTHON", so it can be a program name with args.
+set dummy $am_cv_pathless_PYTHON; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_PYTHON+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $PYTHON in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PYTHON="$PYTHON" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_PYTHON="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+PYTHON=$ac_cv_path_PYTHON
+
+if test -n "$PYTHON"; then
+  echo "$as_me:$LINENO: result: $PYTHON" >&5
+echo "${ECHO_T}$PYTHON" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+    fi
+
+
+
+  echo "$as_me:$LINENO: checking for $am_cv_pathless_PYTHON version" >&5
+echo $ECHO_N "checking for $am_cv_pathless_PYTHON version... $ECHO_C" >&6
+if test "${am_cv_python_version+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  am_cv_python_version=`$PYTHON -c "import sys; print sys.version[:3]"`
+fi
+echo "$as_me:$LINENO: result: $am_cv_python_version" >&5
+echo "${ECHO_T}$am_cv_python_version" >&6
+  PYTHON_VERSION=$am_cv_python_version
+
+
+
+  PYTHON_PREFIX='${prefix}'
+
+  PYTHON_EXEC_PREFIX='${exec_prefix}'
+
+
+
+  echo "$as_me:$LINENO: checking for $am_cv_pathless_PYTHON platform" >&5
+echo $ECHO_N "checking for $am_cv_pathless_PYTHON platform... $ECHO_C" >&6
+if test "${am_cv_python_platform+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  am_cv_python_platform=`$PYTHON -c "import sys; print sys.platform"`
+fi
+echo "$as_me:$LINENO: result: $am_cv_python_platform" >&5
+echo "${ECHO_T}$am_cv_python_platform" >&6
+  PYTHON_PLATFORM=$am_cv_python_platform
+
+
+
+
+
+  pythondir=$PYTHON_PREFIX"/lib/python"$PYTHON_VERSION/site-packages
+
+
+
+  pkgpythondir=\${pythondir}/$PACKAGE
+
+
+
+  pyexecdir=${PYTHON_EXEC_PREFIX}/lib/python${PYTHON_VERSION}/site-packages
+
+
+
+  pkgpyexecdir=\${pyexecdir}/$PACKAGE
+
+
+   if test "$PYTHON" != ""; then
+            echo "$as_me:$LINENO: checking for Python header files" >&5
+echo $ECHO_N "checking for Python header files... $ECHO_C" >&6
+      PYTHON_PREFIX=`($PYTHON -c "import sys; print sys.prefix") 2>/dev/null`
+      PYTHON_VERSION=$am_cv_python_version
+      dirs="$PYTHON_PREFIX/include/python$PYTHON_VERSION
+            $PYTHON_PREFIX/include/$PYTHON_VERSION
+            $PYTHON_PREFIX/include/Py"
+      for i in $dirs; do
+         if test -r "$i/Python.h"; then
+            PYTHON_CFLAGS="-I$i"
+            break
+         fi
+      done
+      if test -z "$PYTHON_CFLAGS"; then
+        echo "$as_me:$LINENO: result: Not found" >&5
+echo "${ECHO_T}Not found" >&6
+      else
+        echo "$as_me:$LINENO: result: $PYTHON_CFLAGS" >&5
+echo "${ECHO_T}$PYTHON_CFLAGS" >&6
+      fi
+
+            echo "$as_me:$LINENO: checking for Python library" >&5
+echo $ECHO_N "checking for Python library... $ECHO_C" >&6
+      dirs="python$PYTHON_VERSION/config python$PYTHON_VERSION/lib python/lib"
+      files="libpython.a libpython$PYTHON_VERSION.a"
+      for i in $dirs; do
+         for f in $files; do
+            if test -r $PYTHON_PREFIX/lib/$i/$f; then
+               PYTHON_LIBS="$PYTHON_PREFIX/lib/$i/$f"
+            fi
+         done
+      done
+      if test -z "$PYTHON_LIBS"; then
+         echo "$as_me:$LINENO: result: Not found" >&5
+echo "${ECHO_T}Not found" >&6
+      else
+         echo "$as_me:$LINENO: result: $PYTHON_LIBS" >&5
+echo "${ECHO_T}$PYTHON_LIBS" >&6
+      fi
+
+                  PYTHON_LDFLAGS="-Wl,--export-dynamic"
+
+   else
+      no_python=yes
+   fi
+
+fi
+
+
+
+if test "$no_python" != "yes" ; then
+  USE_PYTHON_TRUE=
+  USE_PYTHON_FALSE='#'
+else
+  USE_PYTHON_TRUE='#'
+  USE_PYTHON_FALSE=
+fi
+
+if test "$no_python" != "yes"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define USE_PYTHON 1
+_ACEOF
+
+fi
+
+
   succeeded=no
 
   if test -z "$PKG_CONFIG"; then
@@ -13637,6 +13870,13 @@ echo "$as_me: error: conditional \"USE_EXT\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${USE_PYTHON_TRUE}" && test -z "${USE_PYTHON_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"USE_PYTHON\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"USE_PYTHON\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${EXTERNAL_BR1_TRUE}" && test -z "${EXTERNAL_BR1_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"EXTERNAL_BR1\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -14257,6 +14497,20 @@ s,@GUILE_CONFIG@,$GUILE_CONFIG,;t t
 s,@GUILE_CFLAGS@,$GUILE_CFLAGS,;t t
 s,@GUILE_LIBS@,$GUILE_LIBS,;t t
 s,@GUILEDATA@,$GUILEDATA,;t t
+s,@PYTHON@,$PYTHON,;t t
+s,@PYTHON_VERSION@,$PYTHON_VERSION,;t t
+s,@PYTHON_PREFIX@,$PYTHON_PREFIX,;t t
+s,@PYTHON_EXEC_PREFIX@,$PYTHON_EXEC_PREFIX,;t t
+s,@PYTHON_PLATFORM@,$PYTHON_PLATFORM,;t t
+s,@pythondir@,$pythondir,;t t
+s,@pkgpythondir@,$pkgpythondir,;t t
+s,@pyexecdir@,$pyexecdir,;t t
+s,@pkgpyexecdir@,$pkgpyexecdir,;t t
+s,@PYTHON_CFLAGS@,$PYTHON_CFLAGS,;t t
+s,@PYTHON_LIBS@,$PYTHON_LIBS,;t t
+s,@PYTHON_LDFLAGS@,$PYTHON_LDFLAGS,;t t
+s,@USE_PYTHON_TRUE@,$USE_PYTHON_TRUE,;t t
+s,@USE_PYTHON_FALSE@,$USE_PYTHON_FALSE,;t t
 s,@LIBXML2_CFLAGS@,$LIBXML2_CFLAGS,;t t
 s,@LIBXML2_LIBS@,$LIBXML2_LIBS,;t t
 s,@EXTERNAL_BR1_TRUE@,$EXTERNAL_BR1_TRUE,;t t
