Added a pubeval game, cubeful game, and test of previous/next commands.

diff --git a/gnubgtest b/gnubgtest
--- a/gnubgtest
+++ b/gnubgtest
@@ -35,13 +35,51 @@ play
 EOF
 echo '--- Opening move test succeeds.'
 
-# Play a game.
+# Play a game with pubeval.
+./gnubg $dirparam -t << "EOF" > /dev/null || die '--- Pubeval test fails.'
+set automatic game no
+set cube use no
+set player both pubeval
+new game
+EOF
+echo '--- Pubeval test succeeds.'
+
+# Play a cubeless game.
+./gnubg $dirparam -t << "EOF" > /dev/null || die '--- Self-play test fails.'
+set automatic game no
+set cube use no
+set player both gnubg
+new game
+EOF
+echo '--- Self-play test succeeds.'
+
+# Play a cubeful game.
 ./gnubg $dirparam -t << "EOF" > /dev/null || die '--- Self-play test fails.'
 set automatic game no
 set player both gnubg
 new game
 EOF
-echo '--- Self-play test succeeds.'
+echo '--- Cubeful self-play test succeeds.'
+
+# Test game navigation.
+./gnubg $dirparam -t << "EOF" | grep -q '167.*163' || die \
+    '--- Game navigation fails.'
+set rng manual
+set player both human
+new game
+31
+8/5 6/5
+roll
+42
+8/4 6/4
+previous
+previous
+next
+next
+previous
+show pipcount
+EOF
+echo '--- Game navigation succeeds.'
 
 # Test miscellaneous commands.
 ./gnubg $dirparam -t << "EOF" > /dev/null || die \
