Use `-r' option in tests.

diff --git a/gnubgtest b/gnubgtest
--- a/gnubgtest
+++ b/gnubgtest
@@ -22,15 +22,17 @@ rm -f $TEMP
 echo '--- Feature test succeeds.'
 
 # Test without -b; now requires bearoff database.
-./gnubg $dirparam -t -n <> /dev/null || die '--- Bearoff database test fails.'
+./gnubg $dirparam -t -r -n <> /dev/null || die \
+    '--- Bearoff database test fails.'
 echo '--- Bearoff database test succeeds.'
 
 # Test without -n; now requires weights files.
-./gnubg $dirparam -t <> /dev/null || die '--- Neural net weights test fails.'
+./gnubg $dirparam -t -r <> /dev/null || die \
+    '--- Neural net weights test fails.'
 echo '--- Neural net weights test succeeds.'
 
 # Make sure an opening 31 is played correctly.
-./gnubg $dirparam -t << "EOF" | grep -q sGfwATDgc/ABMA || die \
+./gnubg $dirparam -t -r << "EOF" | grep -q sGfwATDgc/ABMA || die \
     '--- Opening move test fails.'
 set player both human
 new game
@@ -42,7 +44,7 @@ EOF
 echo '--- Opening move test succeeds.'
 
 # Play a game with pubeval.
-./gnubg $dirparam -t << "EOF" > /dev/null || die '--- Pubeval test fails.'
+./gnubg $dirparam -t -r << "EOF" > /dev/null || die '--- Pubeval test fails.'
 set automatic game no
 set cube use no
 set player both pubeval
@@ -51,7 +53,7 @@ EOF
 echo '--- Pubeval test succeeds.'
 
 # Play a cubeless game.
-./gnubg $dirparam -t << "EOF" > /dev/null || die '--- Self-play test fails.'
+./gnubg $dirparam -t -r << "EOF" > /dev/null || die '--- Self-play test fails.'
 set automatic game no
 set cube use no
 set player both gnubg
@@ -60,7 +62,7 @@ EOF
 echo '--- Self-play test succeeds.'
 
 # Play a cubeful game.
-./gnubg $dirparam -t << "EOF" > /dev/null || die \
+./gnubg $dirparam -t -r << "EOF" > /dev/null || die \
     '--- Cubeful self-play test fails.'
 set automatic game no
 set player both gnubg
@@ -69,7 +71,7 @@ EOF
 echo '--- Cubeful self-play test succeeds.'
 
 # Test game navigation (and save game for later load test).
-./gnubg $dirparam -t << EOF | grep -q '167.*163' || die \
+./gnubg $dirparam -t -r << EOF | grep -q '167.*163' || die \
     '--- Game navigation fails.'
 set rng manual
 set player both human
@@ -90,7 +92,7 @@ EOF
 echo '--- Game navigation succeeds.'
 
 # Test resignation.
-./gnubg $dirparam -t << "EOF" | grep -q 'a 0, b 4' || die \
+./gnubg $dirparam -t -r << "EOF" | grep -q 'a 0, b 4' || die \
     '--- Resignation test fails.'
 set rng manual
 set player both human
@@ -111,7 +113,7 @@ EOF
 echo '--- Resignation test succeeds.'
 
 # Test beavers.
-./gnubg $dirparam -t << "EOF" | grep -q 'a 0, b 4' || die \
+./gnubg $dirparam -t -r << "EOF" | grep -q 'a 0, b 4' || die \
     '--- Beaver test fails.'
 set rng manual
 set player 0 human
@@ -131,7 +133,8 @@ EOF
 echo '--- Beaver test succeeds.'
 
 # Test saving.
-./gnubg $dirparam -t << EOF | grep -q '163.*161' || die '--- Load test fails.'
+./gnubg $dirparam -t -r << EOF | grep -q '163.*161' || die \
+    '--- Load test fails.'
 set player both human
 load game $TEMP
 show pipcount
@@ -140,7 +143,7 @@ rm -f $TEMP
 echo '--- Load test succeeds.'
 
 # Test miscellaneous commands.
-./gnubg $dirparam -t << "EOF" > /dev/null || die \
+./gnubg $dirparam -t -r << "EOF" > /dev/null || die \
     '--- Miscellaneous test fails.'
 help
 show player
@@ -157,7 +160,7 @@ echo '--- Miscellaneous test succeeds.'
 
 # Test Guile.
 if [ "$GUILE" = "yes" ]; then
-    ./gnubg $dirparam -t << "EOF" > /dev/null || die '--- Guile test fails.'
+    ./gnubg $dirparam -t -r << "EOF" > /dev/null || die '--- Guile test fails.'
 set rng manual
 set player both human
 set automatic game no
