Added self-test.

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -59,6 +59,7 @@ PRE_UNINSTALL = :
 POST_UNINSTALL = :
 AWK = @AWK@
 CC = @CC@
+LN_S = @LN_S@
 MAKEINFO = @MAKEINFO@
 PACKAGE = @PACKAGE@
 VERSION = @VERSION@
@@ -94,7 +95,9 @@ makeweights_SOURCES = makeweights.c
 makeweights_LDADD = -Llib -levent
 makeweights_DEPENDENCIES = lib/libevent.a
 
-EXTRA_DIST = userrng.c copying.awk
+TESTS = gnubgtest
+
+EXTRA_DIST = userrng.c copying.awk gnubgtest
 ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
 mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
 CONFIG_HEADER = config.h
@@ -375,6 +378,7 @@ distcheck: dist
 	mkdir $(distdir)/=build
 	mkdir $(distdir)/=inst
 	dc_install_base=`cd $(distdir)/=inst && pwd`; \
+	$(MAKE) $(AM_MAKEFLAGS) distcheck-hook; \
 	cd $(distdir)/=build \
 	  && ../configure --srcdir=.. --prefix=$$dc_install_base \
 	  && $(MAKE) $(AM_MAKEFLAGS) \
@@ -458,11 +462,37 @@ maintainer-clean-depend:
 	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
 	    >> .deps/$(*F).P; \
 	rm -f .deps/$(*F).pp
+check-TESTS: $(TESTS)
+	@failed=0; all=0; \
+	srcdir=$(srcdir); export srcdir; \
+	for tst in $(TESTS); do \
+	  if test -f $$tst; then dir=.; \
+	  else dir="$(srcdir)"; fi; \
+	  if $(TESTS_ENVIRONMENT) $$dir/$$tst; then \
+	    all=`expr $$all + 1`; \
+	    echo "PASS: $$tst"; \
+	  elif test $$? -ne 77; then \
+	    all=`expr $$all + 1`; \
+	    failed=`expr $$failed + 1`; \
+	    echo "FAIL: $$tst"; \
+	  fi; \
+	done; \
+	if test "$$failed" -eq 0; then \
+	  banner="All $$all tests passed"; \
+	else \
+	  banner="$$failed of $$all tests failed"; \
+	fi; \
+	dashes=`echo "$$banner" | sed s/./=/g`; \
+	echo "$$dashes"; \
+	echo "$$banner"; \
+	echo "$$dashes"; \
+	test "$$failed" -eq 0
 info-am:
 info: info-recursive
 dvi-am:
 dvi: dvi-recursive
 check-am: all-am
+	$(MAKE) $(AM_MAKEFLAGS) check-TESTS
 check: check-recursive
 installcheck-am:
 installcheck: installcheck-recursive
@@ -543,21 +573,24 @@ dvi-recursive mostlyclean-recursive distclean-recursive clean-recursive \
 maintainer-clean-recursive tags tags-recursive mostlyclean-tags \
 distclean-tags clean-tags maintainer-clean-tags distdir \
 mostlyclean-depend distclean-depend clean-depend \
-maintainer-clean-depend info-am info dvi-am dvi check check-am \
-installcheck-am installcheck all-recursive-am install-exec-am \
+maintainer-clean-depend check-TESTS info-am info dvi-am dvi check \
+check-am installcheck-am installcheck all-recursive-am install-exec-am \
 install-exec install-data-am install-data install-am install \
 uninstall-am uninstall all-redirect all-am all installdirs-am \
 installdirs mostlyclean-generic distclean-generic clean-generic \
 maintainer-clean-generic clean mostlyclean distclean maintainer-clean
 
+distcheck-hook:
+	-cp $(srcdir)/gnubg.bd $(srcdir)/gnubg.weights $(distdir)/
 
 copying.c: COPYING copying.awk
-	$(AWK) -f $(srcdir)/copying.awk < $(srcdir)/COPYING > $@
+	$(AWK) -f $(srcdir)/copying.awk < $< > $@
 
 gnubg.bd: makebearoff
-	[ -s $@ ] || ./makebearoff > $@
+	[ -s $@ ] || if [ -s $(srcdir)/gnubg.bd ]; then \
+	$(LN_S) $(srcdir)/gnubg.bd $@; else ./makebearoff > $@; fi
 
-gnubg.weights:
+weights.message:
 	@echo ' ** NOTE: For proper operation, GNU Backgammon requires'
 	@echo ' ** a "gnubg.weights" file containing neural net'
 	@echo ' ** parameters.  This file is not included in the'
@@ -565,9 +598,13 @@ gnubg.weights:
 	@echo ' ** Backgammon home page <http://www.gnu.org/software/gnubg/>'
 	@echo ' ** or generate one by training a neural net yourself.'
 
-gnubg.wd: gnubg.weights
-	if [ -s $(srcdir)/gnubg.weights ]; \
-	then ./makeweights < $(srcdir)/gnubg.weights > $@; fi
+.PHONY: weights.message
+
+gnubg.weights:
+	[ -s $(srcdir)/gnubg.weights ] || $(MAKE) weights.message
+
+gnubg.wd: gnubg.weights makeweights
+	[ -s $@ ] || ./makeweights < $< > $@
 
 .DELETE_ON_ERROR:
 
